### ISSUE TITLE
프로젝트 초기화 세팅

### ISSUE THREAD

**Issue by feanar729** [sooljottagrae/wps_sooljottagrae#1]
-`settings` 모듈 나누기
-`requirements` 내 `development`, `production` 생성 및 분리

**Comment by hyokualexkwon** [comment]
유저 모델 생성은 추가의 별도 Issue로 나누겠습니다.

**Comment by hyokualexkwon** [comment]
-`users` `posts` `tags` `sooljottagrae` application 폴더 생성

**Comment by hyokualexkwon** [comment]
- `slack notification` `Travis CI integration`
